/**
 * List of countries with ISO3 code
 */
export const ISO3CountryCodes =   {
  AFG: "Afghanistan",
  ALB: "Albania",
  DZA: "Algeria",
  AND: "Andorra",
  AGO: "Angola",
  AIA: "Anguilla",
  ATG: "Antigua and Barbuda",
  ARG: "Argentina",
  ARM: "Armenia",
  ABW: "Aruba",
  AUS: "Australia",
  AUT: "Austria",
  AZE: "Azerbaijan",
  BHS: "Bahamas",
  BHR: "Bahrain",
  BGD: "Bangladesh",
  BRB: "Barbados",
  BLR: "Belarus",
  BEL: "Belgium",
  BLZ: "Belize",
  BEN: "Benin",
  BMU: "Bermuda",
  BTN: "Bhutan",
  BOL: "Bolivia",
  BIH: "Bosnia",
  BWA: "Botswana",
  BRA: "Brazil",
  VGB: "British Virgin Islands",
  BRN: "Brunei",
  BGR: "Bulgaria",
  BFA: "Burkina Faso",
  BDI: "Burundi",
  CPV: "Cabo Verde",
  KHM: "Cambodia",
  CMR: "Cameroon",
  CAN: "Canada",
  BES: "Caribbean Netherlands",
  CYM: "Cayman Islands",
  CAF: "Central African Republic",
  TCD: "Chad",
  JEY: "Channel Islands",
  CHL: "Chile",
  CHN: "China",
  COL: "Colombia",
  COG: "Congo",
  CRI: "Costa Rica",
  HRV: "Croatia",
  CUB: "Cuba",
  CUW: "Curaçao",
  CYP: "Cyprus",
  CZE: "Czechia",
  CIV: "Côte d'Ivoire",
  COD: "DRC",
  DNK: "Denmark",
  DJI: "Djibouti",
  DMA: "Dominica",
  DOM: "Dominican Republic",
  ECU: "Ecuador",
  EGY: "Egypt",
  SLV: "El Salvador",
  GNQ: "Equatorial Guinea",
  ERI: "Eritrea",
  EST: "Estonia",
  ETH: "Ethiopia",
  FLK: "Falkland Islands (Malvinas)",
  FRO: "Faroe Islands",
  FJI: "Fiji",
  FIN: "Finland",
  FRA: "France",
  GUF: "French Guiana",
  PYF: "French Polynesia",
  GAB: "Gabon",
  GMB: "Gambia",
  GEO: "Georgia",
  DEU: "Germany",
  GHA: "Ghana",
  GIB: "Gibraltar",
  GRC: "Greece",
  GRL: "Greenland",
  GRD: "Grenada",
  GLP: "Guadeloupe",
  GTM: "Guatemala",
  GIN: "Guinea",
  GNB: "Guinea-Bissau",
  GUY: "Guyana",
  HTI: "Haiti",
  VAT: "Holy See (Vatican City State)",
  HND: "Honduras",
  HKG: "Hong Kong",
  HUN: "Hungary",
  ISL: "Iceland",
  IND: "India",
  IDN: "Indonesia",
  IRN: "Iran",
  IRQ: "Iraq",
  IRL: "Ireland",
  IMN: "Isle of Man",
  ISR: "Israel",
  ITA: "Italy",
  JAM: "Jamaica",
  JPN: "Japan",
  JOR: "Jordan",
  KAZ: "Kazakhstan",
  KEN: "Kenya",
  KWT: "Kuwait",
  KGZ: "Kyrgyzstan",
  LAO: "Lao People's Democratic Republic",
  LVA: "Latvia",
  LBN: "Lebanon",
  LBR: "Liberia",
  LBY: "Libyan Arab Jamahiriya",
  LIE: "Liechtenstein",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MAC: "Macao",
  MKD: "Macedonia",
  MDG: "Madagascar",
  MWI: "Malawi",
  MYS: "Malaysia",
  MDV: "Maldives",
  MLI: "Mali",
  MLT: "Malta",
  MTQ: "Martinique",
  MRT: "Mauritania",
  MUS: "Mauritius",
  MYT: "Mayotte",
  MEX: "Mexico",
  MDA: "Moldova",
  MCO: "Monaco",
  MNG: "Mongolia",
  MNE: "Montenegro",
  MSR: "Montserrat",
  MAR: "Morocco",
  MOZ: "Mozambique",
  MMR: "Myanmar",
  NAM: "Namibia",
  NPL: "Nepal",
  NLD: "Netherlands",
  NCL: "New Caledonia",
  NZL: "New Zealand",
  NIC: "Nicaragua",
  NER: "Niger",
  NGA: "Nigeria",
  NOR: "Norway",
  OMN: "Oman",
  PAK: "Pakistan",
  PSE: "Palestine",
  PAN: "Panama",
  PNG: "Papua New Guinea",
  PRY: "Paraguay",
  PER: "Peru",
  PHL: "Philippines",
  POL: "Poland",
  PRT: "Portugal",
  QAT: "Qatar",
  ROU: "Romania",
  RUS: "Russia",
  RWA: "Rwanda",
  REU: "Réunion",
  KOR: "S. Korea",
  KNA: "Saint Kitts and Nevis",
  LCA: "Saint Lucia",
  MAF: "Saint Martin",
  SPM: "Saint Pierre Miquelon",
  VCT: "Saint Vincent and the Grenadines",
  SMR: "San Marino",
  STP: "Sao Tome and Principe",
  SAU: "Saudi Arabia",
  SEN: "Senegal",
  SRB: "Serbia",
  SYC: "Seychelles",
  SLE: "Sierra Leone",
  SGP: "Singapore",
  SXM: "Sint Maarten",
  SVK: "Slovakia",
  SVN: "Slovenia",
  SOM: "Somalia",
  ZAF: "South Africa",
  SSD: "South Sudan",
  ESP: "Spain",
  LKA: "Sri Lanka",
  BLM: "St. Barth",
  SDN: "Sudan",
  SUR: "Suriname",
  SWZ: "Swaziland",
  SWE: "Sweden",
  CHE: "Switzerland",
  SYR: "Syrian Arab Republic",
  TWN: "Taiwan",
  TZA: "Tanzania",
  THA: "Thailand",
  TLS: "Timor-Leste",
  TGO: "Togo",
  TTO: "Trinidad and Tobago",
  TUN: "Tunisia",
  TUR: "Turkey",
  TCA: "Turks and Caicos Islands",
  ARE: "UAE",
  GBR: "UK",
  USA: "USA",
  UGA: "Uganda",
  UKR: "Ukraine",
  URY: "Uruguay",
  UZB: "Uzbekistan",
  VEN: "Venezuela",
  VNM: "Vietnam",
  ESH: "Western Sahara",
  YEM: "Yemen",
  ZMB: "Zambia",
  ZWE: "Zimbabwe"
}
/**
 * Returns new array by combining proviences data for countries
 *
 * @param {Array} data
 * @param {Array}
 */
export const combineCountryData = (data = []) => {
  const countries = {};
  const worldwide = {
    confirmed: 0,
    recovered: 0,
    deaths: 0,
    active: 0,
    lastUpdate: 0
  };

  data.forEach(
    ({
      countryRegion: country,
      lastUpdate,
      confirmed,
      recovered,
      deaths,
      active,
      iso3
    }) => {
      worldwide.confirmed += confirmed;
      worldwide.recovered += recovered;
      worldwide.deaths += deaths;
      worldwide.active += active;

      if (worldwide.lastUpdate < lastUpdate) {
        worldwide.lastUpdate = lastUpdate;
      }

      if (countries[country]) {
        countries[country].confirmed += confirmed;
        countries[country].recovered += recovered;
        countries[country].deaths += deaths;
        countries[country].active += active;
      } else {
        countries[country] = {
          country,
          lastUpdate,
          confirmed,
          recovered,
          deaths,
          active,
          iso3
        };
      }
    }
  );

  return {
    worldwide,
    countriesData: Object.keys(countries).map(country => countries[country])
  };
};

export const sortOptions = {
  Confirmed: 'confirmed',
  Recovered: 'recovered',
  Deaths: 'deaths'
};
